language: python
python:
  - "3.4"
services: mysql
install:
  - pip install Django==1.9.8 mysqlclient==1.3.7 requests==2.10.0
  - pip install coveralls
script:
  - python3 qipr_approver/manage.py test qipr_approver/
  - coverage run --source qipr_approver/approver/ qipr_approver/approver/manage.py test qipr_approver/ -v 2 
after_success: coveralls