language: python
python:
  - "3.4"
services: mysql
install:
  - pip install Django==1.10.5 mysqlclient==1.3.7 requests==2.10.0
script:
  - cp -r $TRAVIS_BUILD_DIR/qipr_approver/qipr_approver/deploy/settings.example.ini $TRAVIS_BUILD_DIR/qipr_approver/qipr_approver/deploy/settings.ini
  - python3 qipr_approver/manage.py test qipr_approver/
