language: python
python:
  - "3.4"
services: mysql
install:
  - pip install -r $TRAVIS_BUILD_DIR/qipr_approver/requirements.txt 
script:
  - cp -r $TRAVIS_BUILD_DIR/qipr_approver/qipr_approver/deploy/settings.example.ini $TRAVIS_BUILD_DIR/qipr_approver/qipr_approver/deploy/settings.ini
  - python3 qipr_approver/manage.py test qipr_approver/
