# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 20:24
from __future__ import unicode_literals

import approver.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approver', '0006_auto_20170209_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='charter_file',
            field=models.FileField(max_length=200, null=True, upload_to=approver.utils.project_charter_dir),
        ),
    ]
